const PDFDocument = require('pdfkit');

/**
 * Generates an attendance report PDF and pipes it to the response.
 * @param {object[]} records  - Populated Attendance documents
 * @param {string}   month    - "YYYY-MM" label for the report
 * @param {object}   res      - Express response object
 */
const generateAttendancePDF = (records, month, res) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  // Pipe directly to HTTP response
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="attendance-${month}.pdf"`);
  doc.pipe(res);

  // ── Header ──────────────────────────────────────────────────────────────────
  doc
    .fontSize(22)
    .font('Helvetica-Bold')
    .fillColor('#4f46e5')
    .text('Attendify', 50, 50);

  doc
    .fontSize(12)
    .font('Helvetica')
    .fillColor('#64748b')
    .text(`Attendance Report — ${month}`, 50, 78);

  doc
    .moveTo(50, 100)
    .lineTo(545, 100)
    .strokeColor('#e2e8f0')
    .lineWidth(1)
    .stroke();

  // ── Summary stats ────────────────────────────────────────────────────────────
  const total   = records.length;
  const present = records.filter((r) => r.status === 'present').length;
  const absent  = records.filter((r) => r.status === 'absent').length;
  const late    = records.filter((r) => r.status === 'late').length;
  const pct     = total ? Math.round(((present + late) / total) * 100) : 0;

  const stats = [
    { label: 'Total Records', value: total },
    { label: 'Present',       value: present },
    { label: 'Absent',        value: absent },
    { label: 'Late',          value: late },
    { label: 'Attendance %',  value: `${pct}%` },
  ];

  let sx = 50;
  stats.forEach(({ label, value }) => {
    doc.fontSize(9).fillColor('#94a3b8').text(label, sx, 115);
    doc.fontSize(16).font('Helvetica-Bold').fillColor('#0f172a').text(String(value), sx, 128);
    sx += 99;
  });

  doc
    .moveTo(50, 155)
    .lineTo(545, 155)
    .strokeColor('#e2e8f0')
    .stroke();

  // ── Table header ──────────────────────────────────────────────────────────────
  const colX    = [50, 150, 260, 345, 430, 490];
  const headers = ['Student Name', 'Email', 'Date', 'Subject', 'Status', 'Via'];

  doc
    .rect(50, 163, 495, 20)
    .fillColor('#f8fafc')
    .fill();

  doc.font('Helvetica-Bold').fontSize(9).fillColor('#475569');
  headers.forEach((h, i) => doc.text(h, colX[i], 169));

  // ── Table rows ────────────────────────────────────────────────────────────────
  let y = 193;
  const statusColor = { present: '#16a34a', absent: '#dc2626', late: '#d97706' };

  records.forEach((r, idx) => {
    if (y > 760) {
      doc.addPage();
      y = 50;
    }

    // Alternating row fill
    if (idx % 2 === 0) {
      doc.rect(50, y - 4, 495, 18).fillColor('#f8fafc').fill();
    }

    doc.font('Helvetica').fontSize(8.5).fillColor('#334155');
    doc.text(r.user?.name || '—',       colX[0], y, { width: 95, ellipsis: true });
    doc.text(r.user?.email || '—',      colX[1], y, { width: 100, ellipsis: true });
    doc.text(r.date || '—',             colX[2], y, { width: 80 });
    doc.text(r.subject || 'General',    colX[3], y, { width: 80, ellipsis: true });

    // Coloured status
    doc
      .fillColor(statusColor[r.status] || '#475569')
      .text(r.status || '—', colX[4], y, { width: 55 });

    doc.fillColor('#64748b').text(r.markedVia || '—', colX[5], y, { width: 50 });

    y += 18;
  });

  // ── Footer ────────────────────────────────────────────────────────────────────
  doc
    .moveTo(50, 800)
    .lineTo(545, 800)
    .strokeColor('#e2e8f0')
    .stroke();

  doc
    .fontSize(8)
    .fillColor('#94a3b8')
    .text(
      `Generated by Attendify · ${new Date().toLocaleString()}`,
      50, 808,
      { align: 'center', width: 495 }
    );

  doc.end();
};

module.exports = { generateAttendancePDF };
